// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: litchat
  static const package = "litchat";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName => packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/app_launch_img.png
  // ignore: non_constant_identifier_names
  final app_launch_img = const AssetResource("assets/app_launch_img.png", packageName: null);

  /// asset: assets/common/common_arrow_gray_img.png
  // ignore: non_constant_identifier_names
  final common_arrow_gray_img = const AssetResource("assets/common/common_arrow_gray_img.png", packageName: null);

  /// asset: assets/common/common_checked_img.png
  // ignore: non_constant_identifier_names
  final common_checked_img = const AssetResource("assets/common/common_checked_img.png", packageName: null);

  /// asset: assets/common/common_uncheck_img.png
  // ignore: non_constant_identifier_names
  final common_uncheck_img = const AssetResource("assets/common/common_uncheck_img.png", packageName: null);

  /// asset: assets/login/login_apple_btn.png
  // ignore: non_constant_identifier_names
  final login_apple_btn = const AssetResource("assets/login/login_apple_btn.png", packageName: null);

  /// asset: assets/login/login_arrow_right_img.png
  // ignore: non_constant_identifier_names
  final login_arrow_right_img = const AssetResource("assets/login/login_arrow_right_img.png", packageName: null);

  /// asset: assets/login/login_captcha_img.png
  // ignore: non_constant_identifier_names
  final login_captcha_img = const AssetResource("assets/login/login_captcha_img.png", packageName: null);

  /// asset: assets/login/login_email_btn.png
  // ignore: non_constant_identifier_names
  final login_email_btn = const AssetResource("assets/login/login_email_btn.png", packageName: null);

  /// asset: assets/login/login_email_img.png
  // ignore: non_constant_identifier_names
  final login_email_img = const AssetResource("assets/login/login_email_img.png", packageName: null);

  /// asset: assets/login/login_fb_btn.png
  // ignore: non_constant_identifier_names
  final login_fb_btn = const AssetResource("assets/login/login_fb_btn.png", packageName: null);

  /// asset: assets/login/login_gg_btn.png
  // ignore: non_constant_identifier_names
  final login_gg_btn = const AssetResource("assets/login/login_gg_btn.png", packageName: null);

  /// asset: assets/login/login_line_btn.png
  // ignore: non_constant_identifier_names
  final login_line_btn = const AssetResource("assets/login/login_line_btn.png", packageName: null);

  /// asset: assets/login/login_password_img.png
  // ignore: non_constant_identifier_names
  final login_password_img = const AssetResource("assets/login/login_password_img.png", packageName: null);

  /// asset: assets/login/login_password_invisible_img.png
  // ignore: non_constant_identifier_names
  final login_password_invisible_img = const AssetResource("assets/login/login_password_invisible_img.png", packageName: null);

  /// asset: assets/login/login_password_visiable_img.png
  // ignore: non_constant_identifier_names
  final login_password_visiable_img = const AssetResource("assets/login/login_password_visiable_img.png", packageName: null);

  /// asset: assets/login/login_phone_btn.png
  // ignore: non_constant_identifier_names
  final login_phone_btn = const AssetResource("assets/login/login_phone_btn.png", packageName: null);

  /// asset: assets/login/login_phone_img.png
  // ignore: non_constant_identifier_names
  final login_phone_img = const AssetResource("assets/login/login_phone_img.png", packageName: null);

  /// asset: assets/login/register_female_normal_btn.png
  // ignore: non_constant_identifier_names
  final register_female_normal_btn = const AssetResource("assets/login/register_female_normal_btn.png", packageName: null);

  /// asset: assets/login/register_female_selected_btn.png
  // ignore: non_constant_identifier_names
  final register_female_selected_btn = const AssetResource("assets/login/register_female_selected_btn.png", packageName: null);

  /// asset: assets/login/register_male_normal_btn.png
  // ignore: non_constant_identifier_names
  final register_male_normal_btn = const AssetResource("assets/login/register_male_normal_btn.png", packageName: null);

  /// asset: assets/login/register_male_selected_btn.png
  // ignore: non_constant_identifier_names
  final register_male_selected_btn = const AssetResource("assets/login/register_male_selected_btn.png", packageName: null);

  /// asset: assets/login/register_tip_img.png
  // ignore: non_constant_identifier_names
  final register_tip_img = const AssetResource("assets/login/register_tip_img.png", packageName: null);

  /// asset: assets/main/tabbar_chat_img.png
  // ignore: non_constant_identifier_names
  final tabbar_chat_img = const AssetResource("assets/main/tabbar_chat_img.png", packageName: null);

  /// asset: assets/main/tabbar_chat_selected_img.png
  // ignore: non_constant_identifier_names
  final tabbar_chat_selected_img = const AssetResource("assets/main/tabbar_chat_selected_img.png", packageName: null);

  /// asset: assets/main/tabbar_main_img.png
  // ignore: non_constant_identifier_names
  final tabbar_main_img = const AssetResource("assets/main/tabbar_main_img.png", packageName: null);

  /// asset: assets/main/tabbar_main_selected_img.png
  // ignore: non_constant_identifier_names
  final tabbar_main_selected_img = const AssetResource("assets/main/tabbar_main_selected_img.png", packageName: null);

  /// asset: assets/main/tabbar_me_img.png
  // ignore: non_constant_identifier_names
  final tabbar_me_img = const AssetResource("assets/main/tabbar_me_img.png", packageName: null);

  /// asset: assets/main/tabbar_me_selected_img.png
  // ignore: non_constant_identifier_names
  final tabbar_me_selected_img = const AssetResource("assets/main/tabbar_me_selected_img.png", packageName: null);

  /// asset: assets/main/tabbar_room_img.png
  // ignore: non_constant_identifier_names
  final tabbar_room_img = const AssetResource("assets/main/tabbar_room_img.png", packageName: null);

  /// asset: assets/main/tabbar_room_selected_img.png
  // ignore: non_constant_identifier_names
  final tabbar_room_selected_img = const AssetResource("assets/main/tabbar_room_selected_img.png", packageName: null);

  /// asset: assets/navbar/navbar_back_btn.png
  // ignore: non_constant_identifier_names
  final navbar_back_btn = const AssetResource("assets/navbar/navbar_back_btn.png", packageName: null);

  /// asset: assets/navbar/navbar_setting_btn.png
  // ignore: non_constant_identifier_names
  final navbar_setting_btn = const AssetResource("assets/navbar/navbar_setting_btn.png", packageName: null);

}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();

}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/app_launch_img.png
  // ignore: non_constant_identifier_names
  AssetImage app_launch_img() {
    return AssetImage(asset.app_launch_img.keyName);
  }

  /// asset: assets/common/common_arrow_gray_img.png
  // ignore: non_constant_identifier_names
  AssetImage common_arrow_gray_img() {
    return AssetImage(asset.common_arrow_gray_img.keyName);
  }

  /// asset: assets/common/common_checked_img.png
  // ignore: non_constant_identifier_names
  AssetImage common_checked_img() {
    return AssetImage(asset.common_checked_img.keyName);
  }

  /// asset: assets/common/common_uncheck_img.png
  // ignore: non_constant_identifier_names
  AssetImage common_uncheck_img() {
    return AssetImage(asset.common_uncheck_img.keyName);
  }

  /// asset: assets/login/login_apple_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_apple_btn() {
    return AssetImage(asset.login_apple_btn.keyName);
  }

  /// asset: assets/login/login_arrow_right_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_arrow_right_img() {
    return AssetImage(asset.login_arrow_right_img.keyName);
  }

  /// asset: assets/login/login_captcha_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_captcha_img() {
    return AssetImage(asset.login_captcha_img.keyName);
  }

  /// asset: assets/login/login_email_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_email_btn() {
    return AssetImage(asset.login_email_btn.keyName);
  }

  /// asset: assets/login/login_email_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_email_img() {
    return AssetImage(asset.login_email_img.keyName);
  }

  /// asset: assets/login/login_fb_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_fb_btn() {
    return AssetImage(asset.login_fb_btn.keyName);
  }

  /// asset: assets/login/login_gg_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_gg_btn() {
    return AssetImage(asset.login_gg_btn.keyName);
  }

  /// asset: assets/login/login_line_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_line_btn() {
    return AssetImage(asset.login_line_btn.keyName);
  }

  /// asset: assets/login/login_password_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_password_img() {
    return AssetImage(asset.login_password_img.keyName);
  }

  /// asset: assets/login/login_password_invisible_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_password_invisible_img() {
    return AssetImage(asset.login_password_invisible_img.keyName);
  }

  /// asset: assets/login/login_password_visiable_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_password_visiable_img() {
    return AssetImage(asset.login_password_visiable_img.keyName);
  }

  /// asset: assets/login/login_phone_btn.png
  // ignore: non_constant_identifier_names
  AssetImage login_phone_btn() {
    return AssetImage(asset.login_phone_btn.keyName);
  }

  /// asset: assets/login/login_phone_img.png
  // ignore: non_constant_identifier_names
  AssetImage login_phone_img() {
    return AssetImage(asset.login_phone_img.keyName);
  }

  /// asset: assets/login/register_female_normal_btn.png
  // ignore: non_constant_identifier_names
  AssetImage register_female_normal_btn() {
    return AssetImage(asset.register_female_normal_btn.keyName);
  }

  /// asset: assets/login/register_female_selected_btn.png
  // ignore: non_constant_identifier_names
  AssetImage register_female_selected_btn() {
    return AssetImage(asset.register_female_selected_btn.keyName);
  }

  /// asset: assets/login/register_male_normal_btn.png
  // ignore: non_constant_identifier_names
  AssetImage register_male_normal_btn() {
    return AssetImage(asset.register_male_normal_btn.keyName);
  }

  /// asset: assets/login/register_male_selected_btn.png
  // ignore: non_constant_identifier_names
  AssetImage register_male_selected_btn() {
    return AssetImage(asset.register_male_selected_btn.keyName);
  }

  /// asset: assets/login/register_tip_img.png
  // ignore: non_constant_identifier_names
  AssetImage register_tip_img() {
    return AssetImage(asset.register_tip_img.keyName);
  }

  /// asset: assets/main/tabbar_chat_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_chat_img() {
    return AssetImage(asset.tabbar_chat_img.keyName);
  }

  /// asset: assets/main/tabbar_chat_selected_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_chat_selected_img() {
    return AssetImage(asset.tabbar_chat_selected_img.keyName);
  }

  /// asset: assets/main/tabbar_main_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_main_img() {
    return AssetImage(asset.tabbar_main_img.keyName);
  }

  /// asset: assets/main/tabbar_main_selected_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_main_selected_img() {
    return AssetImage(asset.tabbar_main_selected_img.keyName);
  }

  /// asset: assets/main/tabbar_me_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_me_img() {
    return AssetImage(asset.tabbar_me_img.keyName);
  }

  /// asset: assets/main/tabbar_me_selected_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_me_selected_img() {
    return AssetImage(asset.tabbar_me_selected_img.keyName);
  }

  /// asset: assets/main/tabbar_room_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_room_img() {
    return AssetImage(asset.tabbar_room_img.keyName);
  }

  /// asset: assets/main/tabbar_room_selected_img.png
  // ignore: non_constant_identifier_names
  AssetImage tabbar_room_selected_img() {
    return AssetImage(asset.tabbar_room_selected_img.keyName);
  }

  /// asset: assets/navbar/navbar_back_btn.png
  // ignore: non_constant_identifier_names
  AssetImage navbar_back_btn() {
    return AssetImage(asset.navbar_back_btn.keyName);
  }

  /// asset: assets/navbar/navbar_setting_btn.png
  // ignore: non_constant_identifier_names
  AssetImage navbar_setting_btn() {
    return AssetImage(asset.navbar_setting_btn.keyName);
  }

}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();

}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

}
